# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Traducción de Pathologic Classic HD y Pathologic 2
description: Proyecto de traducción al castellano de los videojuegos Pathologic Classic HD y Pathologic 2
url: http://traduccion-pathologic.github.io/
last_updated: true # set to true if you want to display last updated in the footer