# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Traducción de Pathologic Classic HD y Pathologic 2
description: Web oficial de los proyectos de traducción al castellano de Pathologic Classic HD y Pathologic 2.
url: http://traduccion-pathologic.github.io/
last_updated: true # set to true if you want to display last updated in the footer